#!/usr/bin/env bash

# just make a working directory
# code will be checked out from github

# Determine this command name
thisComFull=$(basename $0)
fullCom="${thisComFull%.*}"

# Usage function
function usage() {
    echo "Usage: $fullCom <working_dir> <new tag>"
    echo "       mkdir <working_dir>/<tag>"
    echo "       run newDev"
    echo "       git clone larsoft repositories from github"
    echo
}

create_working_directory() {
  if [ -z "${working_dir}" ]
  then
      echo 'ERROR: the working directory was not specified'
      echo
      usage
      exit 1
  fi
  if [ -d ${working_dir}/${tag} ]
  then
      echo 'ERROR:  ${working_dir}/${tag} already exists!'
      usage
      exit 1
  fi
  mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
  mkdir -p ${working_dir}/${tag}/e19p  ${working_dir}/${tag}/e19d || { echo "ERROR: failed to create ${working_dir}/${tag}/e19p"; exit 1; }
  mkdir -p ${working_dir}/${tag}/c7p  ${working_dir}/${tag}/c7d || { echo "ERROR: failed to create ${working_dir}/${tag}/c7p"; exit 1; }
  cd ${working_dir}/${tag}
  echo "run mrb newDev"
  mrb newDev -f -v ${tag} -q e19:prof -T e19p || exit 1
  mrb newDev -f -v ${tag} -q e19:debug -T e19d || exit 1
  mrb newDev -f -v ${tag} -q c7:prof -T c7p || exit 1
  mrb newDev -f -v ${tag} -q c7:debug -T c7d || exit 1
  echo "source localProductsXXX/setup"
  source e19p/localProducts*/setup
  cd $MRB_SOURCE
  echo "checkout larsoft_suite"
  mrb g --repo-type github --fork larsoft_suite
  echo "checkout larsoftobj_suite"
  mrb g --repo-type github --fork larsoftobj_suite
}

# Determine command options (just -h for help)
while getopts ":h" OPTION
do
    case $OPTION in
        h   ) usage ; exit 0 ;;
        *   ) echo "ERROR: Unknown option" ; usage ; exit 1 ;;
    esac
done

working_dir=${1}
tag=${2}

if [ -z "${working_dir}" ]
then
    echo 'ERROR: no working directory specified'
    usage
    exit 1
fi
if [ -z "${tag}" ]
then
    echo 'ERROR: no tag specified'
    usage
    exit 1
fi

create_working_directory 

exit 0

