#!/usr/bin/env bash

# just make a working directory and checkout packages needed for nulite

# Determine this command name
thisComFull=$(basename $0)
fullCom="${thisComFull%.*}"

# Usage function
function usage() {
    echo "Usage: $fullCom <working_dir> <new tag> <base qualifier>"
    echo "   This script will do the following:"
    echo "       mkdir <working_dir>/<tag>"
    echo "       run newDev"
    echo "       git clone nulite repositories from redmine"
    echo "   The base qualifier should be one of e17, e19, c7 etc."
    echo
}

create_working_directory() {
  if [ -z "${working_dir}" ]
  then
      echo 'ERROR: the working directory was not specified'
      echo
      usage
      exit 1
  fi
  if [ -d ${working_dir}/${tag} ]
  then
      echo 'INFO:  ${working_dir}/${tag} already exists!'
      echo 'INFO:  adding build directories for ${basequal}'
  fi
  mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
  mkdir -p ${working_dir}/${tag}/${basequal}p  ${working_dir}/${tag}/${basequal}d || \
     { echo "ERROR: failed to create ${working_dir}/${tag}/${basequal}p"; exit 1; }
  cd ${working_dir}/${tag}
  echo "run mrb newDev"
  mrb newDev -f -v ${tag} -q ${basequal}:prof -T ${basequal}p || exit 1
  mrb newDev -f -v ${tag} -q ${basequal}:debug -T ${basequal}d || exit 1
  echo "source localProductsXXX/setup"
  source ${basequal}p/localProducts*/setup
  cd $MRB_SOURCE
  echo "checkout nu_suite"
  mrb g nu_suite
}

# Determine command options (just -h for help)
while getopts ":h" OPTION
do
    case $OPTION in
        h   ) usage ; exit 0 ;;
        *   ) echo "ERROR: Unknown option" ; usage ; exit 1 ;;
    esac
done

working_dir=${1}
tag=${2}
basequal=${3}

if [ -z "${working_dir}" ]
then
    echo 'ERROR: no working directory specified'
    usage
    exit 1
fi
if [ -z "${tag}" ]
then
    echo 'ERROR: no tag specified'
    usage
    exit 1
fi
if [ -z "${basequal}" ]
then
    echo 'ERROR: no basequal specified'
    usage
    exit 1
fi

create_working_directory 

exit 0
