#!/usr/bin/env bash

# This script allows us to mimic git flow, but do the steps in a set order

# work flow
# mrb newDev ...
# mrb g larsoft_suite, larbatch, larutils
# mrb g dunetpc, duneutil
# mrb g uboone_suite
# mrb g argoneutcode
# mrb g lariatsoft
# tagLar start <tag>
# tagLar update <tag>
# mrb uv other products if necessary
# verify build, test, and install 
# tagLar tag <tag>
# now do the official build and distribution
# tagLar merge <tag>
# this is the final step to merge the changes with the develop branch

# cetbuildtools: 
#  increment-version -u --client-dir $MRB_SOURCE/lar*
# relevant options are -M, -m, -u 


# Determine this command name
thisComFull=$(basename $0)
fullCom="${thisComFull%.*}"

# Usage function
function usage() {
    echo "Usage: $fullCom <start|update|tag|merge> <tag>"
    echo "Usage: $fullCom feature <new tag>"
    echo "Usage: $fullCom patch <new tag> <existing tag>"
    echo "Usage: $fullCom branch <new branch> <existing tag>"
    echo "Usage: $fullCom tagbranch <existing branch> <new tag>"
    echo "Usage: $fullCom mkdir <new tag> <working_dir>"
    echo "   mkdir  - mkdir <working_dir>/<tag>, run newDev, then checkout larsoft_suite and experiment code"
    echo "   start - create release/<tag> branch"
    echo "   feature - create feature/<tag> branch"
    echo "   patch - create release/<tag> branch based on existing tag"
    echo "   branch - create <branch> branch based on existing tag"
    echo "   use - use existing <branch> branch"
    echo "   update - modify product_deps to use <tag>"
    echo "   tag - merge changes with master and tag"
    echo "   tagbranch - tag the designated branch"
    echo "   force - merge changes with master and force update of existing tag"
    echo "   merge - merge changes with develop"
    echo
    echo "FOR EXPERT USE ONLY"

}

# mkdir is a special case
create_working_directory() {
  if [ -z "${working_dir}" ]
  then
      echo 'ERROR: the working directory was not specified'
      echo
      usage
      exit 1
  fi
  if [ -d ${working_dir}/${tag} ]
  then
      echo 'ERROR:  ${working_dir}/${tag} already exists!'
      usage
      exit 1
  fi
  mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
  #mkdir -p ${working_dir}/${tag}/p  ${working_dir}/${tag}/d || { echo "ERROR: failed to create ${working_dir}/${tag}/p"; exit 1; }
  mkdir -p ${working_dir}/${tag}/e17p  ${working_dir}/${tag}/e17d || { echo "ERROR: failed to create ${working_dir}/${tag}/e17p"; exit 1; }
  mkdir -p ${working_dir}/${tag}/c2p  ${working_dir}/${tag}/c2d || { echo "ERROR: failed to create ${working_dir}/${tag}/c2p"; exit 1; }
  cd ${working_dir}/${tag}
  echo "run mrb newDev"
  #mrb newDev -f -v ${tag} -q e15:prof -T p || exit 1
  #mrb newDev -f -v ${tag} -q e15:debug -T d || exit 1
  mrb newDev -f -v ${tag} -q e17:prof -T e17p || exit 1
  mrb newDev -f -v ${tag} -q e17:debug -T e17d || exit 1
  mrb newDev -f -v ${tag} -q c2:prof -T c2p || exit 1
  mrb newDev -f -v ${tag} -q c2:debug -T c2d || exit 1
  echo "source localProductsXXX/setup"
  source e17p/localProducts*/setup
  cd $MRB_SOURCE
  echo "checkout larsoft_suite"
  mrb g larsoft_suite
  echo "checkout larsoftobj_suite"
  mrb g larcoreobj
  mrb g larcorealg
  mrb g lardataobj
  mrb g lardataalg
  mrb g larsoftobj
  echo "checkout larbatch"
  mrb g larbatch
  echo "checkout larutils"
  mrb g larutils
  echo "checkout larpandoracontent"
  mrb g larpandoracontent
  # look for extra options 
  if [ -z "${extra_options}" ]; then
  echo "checkout dunetpc"
  mrb g dunetpc
  echo "checkout duneutil"
  mrb g duneutil
  echo "checkout lariatsoft"
  mrb g lariatsoft
  mrb g lariatfragments
  mrb g lariatutil
  #mrb g -d lariatfragments lariat-online-lariatfragments
  #mrb g -d lariatutil lardbt-lariatutil
  echo "checkout sbndcode"
  mrb g sbndcode
  mrb g sbndutil
  echo "checkout uboonecode"
  mrb  g uboone_suite
  echo "checkout argoneutcode"
  mrb g argoneutcode
  ##echo "checkout icaruscode"
  ##mrb g icaruscode
  elif [[ ${extra_options} == "argoneut" ]]; then
  echo "checkout argoneutcode"
  mrb g argoneutcode
  elif [[ ${extra_options} == "dune" ]]; then
  echo "checkout dunetpc"
  mrb g dunetpc
  echo "checkout duneutil"
  mrb g duneutil
  elif [[ ${extra_options} == "lariat" ]]; then
  echo "checkout lariatsoft"
  mrb g lariatsoft
  mrb g -d lariatfragments lariat-online-lariatfragments
  mrb g -d lariatutil lardbt-lariatutil
  elif [[ ${extra_options} == "sbnd" ]]; then
  echo "checkout sbndcode"
  mrb g sbndcode
  mrb g sbndutil
  elif [[ ${extra_options} == "uboone" ]]; then
  echo "checkout uboonecode"
  mrb  g uboone_suite
  else
    echo "ERROR: unrecognized option ${extra_options}"
    exit 1
  fi
}

# Determine command options (just -h for help)
while getopts ":h" OPTION
do
    case $OPTION in
        h   ) usage ; exit 0 ;;
        *   ) echo "ERROR: Unknown option" ; usage ; exit 1 ;;
    esac
done

# Capture the tag
flow=${1}
tag=${2}
extra=${3}
extra_options=${4}
if [ -z "${flow}" ]
then
    echo 'ERROR: no options specified'
    usage
    exit 1
fi
if [ -z "${tag}" ]
then
    echo 'ERROR: no tag specified'
    usage
    exit 1
fi

if [ "${flow}" = "mkdir" ]
then
  working_dir=${extra}
  create_working_directory 
  exit 0
fi

if [ -z "${MRB_SOURCE}" ]
then
    echo 'ERROR: MRB_SOURCE must be defined'
    echo '       source the appropriate localProductsXXX/setup'
    exit 1
fi

if [ ! -r $MRB_SOURCE/CMakeLists.txt ]; then
    echo "$MRB_SOURCE/CMakeLists.txt not found"
    exit 1
fi

# find the directories
# ignore any directory that does not contain ups/product_deps
list=`ls $MRB_SOURCE -1`
for file in $list
do
   if [ -d $file ]
   then
     if [ -r $file/ups/product_deps ]
     then
       pkglist="$file $pkglist"
     fi
   fi
done

if [ "${flow}" = "start" ]
then
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     git checkout develop
     git checkout -b release/${tag}
     okflow=$?
     if [ ! ${okflow} ]
     then
	echo "${REP} git checkout -b release failure: ${okflow}"
	exit 1
     fi
  done
fi

if [ "${flow}" = "feature" ]
then
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     git checkout develop
     git checkout -b feature/${tag}
     okflow=$?
     if [ ! ${okflow} ]
     then
	echo "${REP} git co -b feature failure: ${okflow}"
	exit 1
     fi
  done
fi

if [ "${flow}" = "patch" ]
then
  oldtag=${extra}
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     git checkout ${oldtag}
     git checkout -b release/${tag}
     okflow=$?
     if [ ! ${okflow} ]
     then
	echo "${REP} git checkout -b release failure: ${okflow}"
	exit 1
     fi
  done
fi

if [ "${flow}" = "branch" ]
then
  oldtag=${extra}
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     git checkout ${oldtag}
     git checkout -b ${tag}
     okflow=$?
     if [ ! ${okflow} ]
     then
	echo "${REP} git checkout -b ${tag} failure: ${okflow}"
	exit 1
     fi
  done
fi

if [ "${flow}" = "use" ]
then
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     git checkout ${tag}
     okflow=$?
     if [ ! ${okflow} ]
     then
	echo "${REP} git checkout ${tag} failure: ${okflow}"
	exit 1
     fi
  done
fi

if [ "${flow}" = "update" ]
then
  for REP in $pkglist
  do
     mrb uv ${REP} ${tag}
  done
fi

if [ "${flow}" = "tag" ]
then
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     version=`grep ${REP} ups/product_deps | grep parent | sed -e 's/[[:space:]]/ /g' | cut -f3 -d " "`
     echo "begin ${REP} ${version}"
     git commit -m"${REP} ${version} for larsoft ${tag}" ups/product_deps  || exit 1
     git checkout master  || exit 1
     git merge -m"${REP} ${version} for larsoft ${tag}" release/${tag}   || exit 1
     git tag -a -m"${REP} ${version} for larsoft ${tag}" ${version}  || exit 1
     git push origin master ${version} || exit 1
  done
fi

if [ "${flow}" = "tagbranch" ]
then
  for REP in $pkglist
  do
     echo
     echo "begin ${REP} ${version}"
     cd ${MRB_SOURCE}/${REP}
     # make sure we are on the expected branch
     git checkout ${branch}  || exit 1
     version=`grep ${REP} ups/product_deps | grep parent | sed -e 's/[[:space:]]/ /g' | cut -f3 -d " "`
     git commit -m"${REP} ${version} for larsoft ${tag}" ups/product_deps  || exit 1
     git tag -a -m"${REP} ${version} for larsoft ${tag}" ${version}  || exit 1
     git push origin ${branch} ${version} || exit 1
  done
fi

if [ "${flow}" = "force" ]
then
  for REP in $pkglist
  do
     cd ${MRB_SOURCE}/${REP}
     version=`grep ${REP} ups/product_deps | grep parent | sed -e 's/[[:space:]]/ /g' | cut -f3 -d " "`
     echo "begin ${REP} ${version}"
     ##rm -f ups/product_deps.bak
     git commit -m"${REP} ${version} for larsoft ${tag}" ups/product_deps  || exit 1
     git checkout master  || exit 1
     ##git diff release/${tag}   || exit 1
     git merge -m"${REP} ${version} for larsoft ${tag}" release/${tag}   || exit 1
     git tag -a -f -m"${REP} ${version} for larsoft ${tag}" ${version}  || exit 1
     git push origin master  || exit 1
     git push --force --tags  || exit 1
  done
fi

if [ "${flow}" = "merge" ]
then
  for REP in $pkglist
  do
     set -x 
     cd ${MRB_SOURCE}/${REP}
     echo "begin ${REP}"
     ##git checkout master  || exit 1
     ##git pull  || exit 1
     git checkout develop  || exit 1
     git pull  || exit 1
     git merge -m"larsoft ${tag}" release/${tag}  || exit 1
     git push origin develop  || exit 1
     ##git branch -d release/${tag}   || exit 1
  done
fi


exit 0
