#!/usr/bin/perl -w

use strict;
use warnings;

if( $#ARGV < 2  ) {
    print "\n";
    print "USAGE: calculatePatchUpdate <input line>\n";
    print "\n";
    exit 1;
}

my $input = $ARGV[0];
my $package = $ARGV[1];
my $version = $ARGV[2];

if( $input ne "parent" ) {
    print "\n";
    print "This script is meant to be called with the output of \n";
    print "  grep ^parent <package>/ups/product_deps \n";
    print "\n";
    exit 1;
}

##print "found $input $package $version\n";

my @v = split('_', $version);
if( ! $v[3] ) { $v[3]="00"; }
##print "version parts $v[0] $v[1] $v[2] $v[3]\n";
# increment patch by one
++$v[3];
my $newver = $v[0]."_".$v[1]."_".$v[2]."_".$v[3];
##print "version $version will become $newver\n";
print "$newver\n";

exit(0);
