#!/usr/bin/env bash

# checkout uboone code and larsoft using explicit branches

# Determine this command name
thisComFull=$(basename $0)
fullCom="${thisComFull%.*}"

# Usage function
function usage() {
    echo "Usage: $fullCom <working_dir> <tag> <larsoft branch> [<uboone branch>]"
    echo "   create subdirectory <working_dir>/<tag>, run newDev, then checkout larsoft_suite and experiment code"
    echo "   create subdirectories for e17 and c2 builds"
    echo
    echo "FOR EXPERT USE ONLY"

}

# mkdir is a special case
create_working_directory() {
  if [ -d ${working_dir}/${tag} ]
  then
      echo 'ERROR:  ${working_dir}/${tag} already exists!'
      usage
      exit 1
  fi
  mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
  mkdir -p ${working_dir}/${tag}/e17p  ${working_dir}/${tag}/e17d || { echo "ERROR: failed to create ${working_dir}/${tag}/e17p"; exit 1; }
  mkdir -p ${working_dir}/${tag}/c2p  ${working_dir}/${tag}/c2d || { echo "ERROR: failed to create ${working_dir}/${tag}/c2p"; exit 1; }
  cd ${working_dir}/${tag}
  echo "run mrb newDev"
  mrb newDev -f -v ${tag} -q e17:prof -T e17p || exit 1
  mrb newDev -f -v ${tag} -q e17:debug -T e17d || exit 1
  mrb newDev -f -v ${tag} -q c2:prof -T c2p || exit 1
  mrb newDev -f -v ${tag} -q c2:debug -T c2d || exit 1
  echo "source localProductsXXX/setup"
  source e17p/localProducts*/setup
  cd $MRB_SOURCE
  echo "checkout larsoft_suite"
  mrb g -b ${larbranch} larsoft_suite
  echo "checkout larsoftobj_suite"
  mrb g -b ${larbranch} larsoftobj_suite
  echo "checkout larpandoracontent"
  mrb g larpandoracontent
  echo "checkout uboonecode"
  mrb  g  -b ${ubranch} uboone_suite
}

# Determine command options (just -h for help)
while getopts ":h" OPTION
do
    case $OPTION in
        h   ) usage ; exit 0 ;;
        *   ) echo "ERROR: Unknown option" ; usage ; exit 1 ;;
    esac
done

working_dir=${1}
tag=${2}
larbranch=${3}
ubranch=${4}

if [ -z "${working_dir}" ]
then
    echo 'ERROR: no working_dir specified'
    usage
    exit 1
fi
if [ -z "${tag}" ]
then
    echo 'ERROR: no tag specified'
    usage
    exit 1
fi
if [ -z "${larbranch}" ]
then
    echo 'ERROR: no larsoft branch specified'
    usage
    exit 1
fi
if [ -z "${ubranch}" ]
then
    echo 'INFO: MicroBooNE branch not specified, using ${larbranch}'
    ubranch=${larbranch}
fi

  create_working_directory 
  exit 0

