#!/usr/bin/env bash

# checkout uboone code and larsoft using explicit branches

# Determine this command name
thisComFull=$(basename $0)
fullCom="${thisComFull%.*}"

# Usage function
function usage() {
    echo "Usage: $fullCom [-e <experiment>] [-q <base qualifier>] <working_dir> <new patch tag> <larsoft branch> [<experiment branch>]"
    echo "   create subdirectory <working_dir>/<new patch tag>, run newDev, then checkout code"
    echo "  options:"
    echo "   -q <base qualifier>: create subdirectories the specified qualifier"
    echo "      If the base qualifier is not specified, create subdirectories for e26"
    echo "      The base qualifier should be one of e20, e26, c14 etc."
    echo "      To use more than one qualifier, repeat the command with another qualifier."
    echo "   -e <experiment>: checkout larsoft and experiment code"
    echo "      experiment must be one of argoneut, dune, lariat, icarus, sbnd, or uboone"
    echo "      If no experiment is specified, only checkout larsoft."
    echo "   -d - very simple dry run, no changes will be made"
    echo
    echo "FOR EXPERT USE ONLY"

}

create_working_directory() {
  if [ -d ${working_dir}/${newtag} ]
  then
      echo 'INFO:  ${working_dir}/${newtag} already exists!'
      echo 'INFO:  adding build directories for ${basequal}'
  else
      mkdir -p ${working_dir}/${newtag} || \
         { echo "ERROR: failed to create ${working_dir}/${newtag}"; exit 1; }
  fi
  mkdir -p ${working_dir}/${newtag}/${basequal}p  ${working_dir}/${newtag}/${basequal}d || \
    { echo "ERROR: failed to create ${working_dir}/${newtag}/${basequal}p"; exit 1; }
  cd ${working_dir}/${newtag}
  echo "run mrb newDev"
  mrb newDev -f -v ${newtag} -q ${basequal}:prof -T ${basequal}p || exit 1
  mrb newDev -f -v ${newtag} -q ${basequal}:debug -T ${basequal}d || exit 1
  echo "source localProductsXXX/setup"
  source ${basequal}p/localProducts*/setup
  cd $MRB_SOURCE
  echo "checkout larsoft packages"
  if [ ! -d ${MRB_SOURCE}/larsoft ]; then
    echo "checkout larsoft_suite"
    mrb g larsoft_suite
  fi
  if [ ! -d ${MRB_SOURCE}/larsoftobj ]; then
    echo "checkout larsoftobj_suite"
    mrb g larsoftobj_suite
  fi
  echo "get larpandoracontent"
  if [ ! -d ${MRB_SOURCE}/larpandoracontent ]; then
    echo "checkout larpandoracontent"
    mrb g larpandoracontent
  fi
  echo "get the requested branch"
  dogit "checkout ${larbranch}"
  # check to see if the branch exists
  # ignore any directory that does not contain ups/product_deps
  list=`ls $MRB_SOURCE -1`
  for file in $list
  do
   if [ -d $file ]
   then
     if [ -r $file/ups/product_deps ]
     then
       pkglist="$file $pkglist"
     fi
   fi
  done
  for REP in $pkglist
  do
    cd ${MRB_SOURCE}/${REP}
    curbranch=`git branch --show-current`
    if [[ ${curbranch} != ${larbranch} ]]; then
	    cd ${MRB_SOURCE}
	    rm -rf ${REP}
    fi
  done
  cd ${MRB_SOURCE}
  mrb uc
  #mrb g -b ${larbranch} larsoft_suite
  #echo "checkout larsoftobj_suite"
  #mrb g -b ${larbranch} larsoftobj_suite
  # now get the appropriate experiment code
  if [[ ${experiment} == "argoneut" ]]; then
    echo "checkout argoneutcode"
    mrb g argoneutcode
  elif [[ ${experiment} == "dune" ]]; then
    echo "checkout dune"
    mrb g -b ${expbranch} dune_suite
  elif [[ ${experiment} == "lariat" ]]; then
    echo "checkout lariat"
    mrb g lariat_suite
  elif [[ ${experiment} == "icarus" ]]; then
    echo "checkout icarus"
    mrb g -b ${expbranch} sbn_suite
  elif [[ ${experiment} == "sbnd" ]]; then
    echo "checkout sbnd"
    mrb g -b ${expbranch} sbn_suite
  elif [[ ${experiment} == "uboone" ]]; then
    echo "checkout uboone"
    mrb  g  -b ${expbranch} uboone_suite
  else
    echo "no experiment specified - just checking out larsoft"
  fi
}

##################
# start here

# Determine command options (just -h for help)
while getopts :e:q:dh OPTION
do
    case ${OPTION} in
        e   ) experiment="$OPTARG"; echo "found experiment $OPTARG" ;;
	q   ) basequal="$OPTARG" ;;
        d   ) dry_run=true ;;
        h   ) usage ; exit 0 ;;
        *   ) echo "ERROR: Unknown option" ; usage ; exit 1 ;;
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

working_dir=${1}
newtag=${2}
larbranch=${3}
expbranch=${4}

mrbt=`type mrb`
echo "mrb is $mrbt"

# Some sanity checks -

# Make sure we have ups
if [ -z ${UPS_DIR} ]
then
   echo "ERROR: please setup ups and mrb"
   exit 1
fi
# Check mrb
if [ -z ${MRB_DIR} ]
then
   echo "ERROR: please setup mrb and define \${MRB_PROJECT}"
   exit 1
fi
if [ -z ${MRB_PROJECT} ]
then
    echo 'ERROR: MRB_PROJECT is not defined.'
    echo '       Please set \${MRB_PROJECT} to the master product (e.g., larsoft, uboone, etc.)'
    exit 1
fi
if [ -z "${working_dir}" ]
then
    echo 'ERROR: no working_dir specified'
    usage
    exit 1
fi
if [ -z "${newtag}" ]
then
    echo 'ERROR: no new tag specified'
    usage
    exit 1
fi
if [ -z "${larbranch}" ]
then
    echo 'ERROR: no larsoft branch specified'
    usage
    exit 1
fi
if [ -z "${expbranch}" ]
then
    echo 'INFO: experiment branch not specified, using ${larbranch}'
    expbranch=${larbranch}
fi
if [ -z "${experiment}" ]
then
    echo 'INFO: no experiment specified'
fi
if [ -z "${basequal}" ]
then
    echo 'INFO: no base qualifier specified, will use e26'
    basequal=e26
fi
if [[ ${dry_run} == "true" ]]; then
  echo "DRY RUN: working_dir is ${working_dir}"
  echo "DRY RUN: newtag is ${newtag}"
  echo "DRY RUN: larbranch is ${larbranch}"
  echo "DRY RUN: expbranch is ${expbranch}"
  echo "DRY RUN: basequal is ${basequal}"
else
  create_working_directory 
fi
  exit 0

